version: "3.8"

services:
  postgres:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data_notifyme/
    ports:
      - 5432:5432
    env_file: .env

  redis:
    image: redis:6-alpine

  api:
    build:
      context: ./src/backend
    command: >
      sh -c "uvicorn app.main:app --reload --workers 5 --host 0.0.0.0 --port 8000 --root-path /api --proxy-headers"
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - redis
      - postgres

  web:
    build:
      context: ./src/web
    ports:
      - 8080:8080

  nginx:
    build:
      context: ./src/nginx
    restart: always
    ports:
      - 80:80
    env_file: .env
    depends_on:
      - api
      - web

volumes:
  postgres_data:
